#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=4,walltime=5:00:00

[ $PBS_O_WORKDIR ] && cd $PBS_O_WORKDIR

## modules
echo "Loading modules"
module load ants
module unload matlab
module load matlab/2017a
module load spm/8
module unload python
module load dipy/dev
module load nodejs
module unload mrtrix/0.2.12 
module load mrtrix/0.3.15 
echo "Finished loading modules"

export PYTHONPATH=/N/u/brlife/git/nibabel:$PYTHONPATH

# Check the inputs subject id
echo "Check the inputs subject id"
t1_sub1_id=`jq -r '._inputs[0].meta.subject' config.json`
afq_sub1_id=`jq -r '._inputs[1].meta.subject' config.json`
t1_sub2_id=`jq -r '._inputs[2].meta.subject' config.json`
if [ $t1_sub1_id == $afq_sub1_id ]; then
	echo "Inputs subject IDs correctly inserted"
else
	echo "Inputs subject IDs incorrectly inserted. Check them again."
	exit 1
fi

# AFQ conversion
echo "AFQ conversion to trk"
matlab -nosplash -nodisplay -r "afqConverter1()";

ret=$?
if [ ! $ret -eq 0 ]; then
	echo "AFQ conversion failed"
	echo $ret > finished
	exit $ret
fi

# Run compute transformation and registration
echo "Computing ANTs transformation and registration"
./voxel_based_transformation_registration_t1_karst.sh ${t1_sub1_id} ${t1_sub2_id}


# Build a fg structure from tck registered with T1
while read tract_name; do         

    echo "Tract name: $tract_name"; 

    tck_filename=\'tracts_tck/sub-${t1_sub1_id}_space_${t1_sub2_id}_var-ant4t1w_set-${tract_name}_tract.tck\';
    tract_filename=\'$tract_name\';
    echo $tck_filename;
    echo $tract_filename;
    matlab -nosplash -nodisplay -r "my_convert_tck2fg($tck_filename, $tract_filename)";

    if [ -f $tract_name'.mat' ]; then 
    	echo "tck2fg conversion done."
    else 
	echo "tck2fg conversion failed."
	exit 1
    fi

done < tract_name_list.txt

# Merge the fg structures and create the files for the wmc structure
echo "Creating the WMC structure"
output_filename=${t1_sub1_id}_space_${t1_sub2_id}'_var-partial_tract.tck';
python build_partial_tractogram.py -tracts_tck_dir 'tracts_tck' -out ${output_filename};
matlab -nosplash -nodisplay -r "my_fg_merge()";

if [ -f 'output.mat' ]; then 
    	echo "WCM structure created."
else 
	echo "WCM structure missing."
	exit 1
fi


echo "Complete"
